version: "3.7"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  express:
    build:
      dockerfile: Docker.express
  client:
    build:
      dockerfile: Docker.web